-- Add currency_code to countries (ISO 4217, e.g. USD, INR, GBP)
ALTER TABLE countries ADD COLUMN IF NOT EXISTS currency_code text NOT NULL DEFAULT 'USD';

UPDATE countries SET currency_code = 'GBP' WHERE id = 'UK';
UPDATE countries SET currency_code = 'USD' WHERE id = 'USA';
UPDATE countries SET currency_code = 'JPY' WHERE id = 'Japan';
UPDATE countries SET currency_code = 'SGD' WHERE id = 'Singapore';
UPDATE countries SET currency_code = 'AED' WHERE id = 'UAE';
UPDATE countries SET currency_code = 'EUR' WHERE id = 'France';
UPDATE countries SET currency_code = 'CNY' WHERE id = 'China';
UPDATE countries SET currency_code = 'INR' WHERE id = 'India';
UPDATE countries SET currency_code = 'AUD' WHERE id = 'Australia';
UPDATE countries SET currency_code = 'CAD' WHERE id = 'Canada';
UPDATE countries SET currency_code = 'EUR' WHERE id = 'Germany';
UPDATE countries SET currency_code = 'EUR' WHERE id = 'Spain';
UPDATE countries SET currency_code = 'EUR' WHERE id = 'Italy';
UPDATE countries SET currency_code = 'EUR' WHERE id = 'Netherlands';
UPDATE countries SET currency_code = 'CHF' WHERE id = 'Switzerland';
UPDATE countries SET currency_code = 'EUR' WHERE id = 'Austria';
UPDATE countries SET currency_code = 'SEK' WHERE id = 'Sweden';
UPDATE countries SET currency_code = 'DKK' WHERE id = 'Denmark';
UPDATE countries SET currency_code = 'NOK' WHERE id = 'Norway';
UPDATE countries SET currency_code = 'EUR' WHERE id = 'Finland';
UPDATE countries SET currency_code = 'EUR' WHERE id = 'Ireland';
UPDATE countries SET currency_code = 'EUR' WHERE id = 'Portugal';
UPDATE countries SET currency_code = 'CZK' WHERE id = 'Czech Republic';
UPDATE countries SET currency_code = 'PLN' WHERE id = 'Poland';
UPDATE countries SET currency_code = 'EUR' WHERE id = 'Belgium';
UPDATE countries SET currency_code = 'TRY' WHERE id = 'Turkey';
UPDATE countries SET currency_code = 'RUB' WHERE id = 'Russia';
UPDATE countries SET currency_code = 'EUR' WHERE id = 'Greece';
UPDATE countries SET currency_code = 'HUF' WHERE id = 'Hungary';
UPDATE countries SET currency_code = 'KRW' WHERE id = 'South Korea';
UPDATE countries SET currency_code = 'TWD' WHERE id = 'Taiwan';
UPDATE countries SET currency_code = 'IDR' WHERE id = 'Indonesia';
UPDATE countries SET currency_code = 'PHP' WHERE id = 'Philippines';
UPDATE countries SET currency_code = 'VND' WHERE id = 'Vietnam';
UPDATE countries SET currency_code = 'SAR' WHERE id = 'Saudi Arabia';
UPDATE countries SET currency_code = 'QAR' WHERE id = 'Qatar';
UPDATE countries SET currency_code = 'ILS' WHERE id = 'Israel';
UPDATE countries SET currency_code = 'MXN' WHERE id = 'Mexico';
UPDATE countries SET currency_code = 'BRL' WHERE id = 'Brazil';
UPDATE countries SET currency_code = 'ARS' WHERE id = 'Argentina';
UPDATE countries SET currency_code = 'COP' WHERE id = 'Colombia';
UPDATE countries SET currency_code = 'PEN' WHERE id = 'Peru';
UPDATE countries SET currency_code = 'CLP' WHERE id = 'Chile';
UPDATE countries SET currency_code = 'ZAR' WHERE id = 'South Africa';
UPDATE countries SET currency_code = 'NGN' WHERE id = 'Nigeria';
UPDATE countries SET currency_code = 'KES' WHERE id = 'Kenya';
UPDATE countries SET currency_code = 'EGP' WHERE id = 'Egypt';
UPDATE countries SET currency_code = 'MAD' WHERE id = 'Morocco';
UPDATE countries SET currency_code = 'ETB' WHERE id = 'Ethiopia';
UPDATE countries SET currency_code = 'NZD' WHERE id = 'New Zealand';
UPDATE countries SET currency_code = 'THB' WHERE id = 'Thailand';
UPDATE countries SET currency_code = 'MYR' WHERE id = 'Malaysia';
